/**
 * PDF Report Generator for SafeStreets
 * Clean, professional report with dot-style metrics visualization
 */

import jsPDF from 'jspdf';
import type { Location, WalkabilityMetrics, DataQuality } from '../types';

// Placeholder type since mapillary was removed
interface MapillaryImage {
  id: string;
  thumb_2048_url: string;
  captured_at: string;
  compass_angle: number;
}

interface ReportData {
  location: Location;
  metrics: WalkabilityMetrics;
  dataQuality: DataQuality;
  mapElement?: HTMLElement;
  mapillaryImages?: MapillaryImage[];
}

// Color palette
const COLORS = {
  green: [16, 185, 129],
  amber: [245, 158, 11],
  orange: [249, 115, 22],
  red: [239, 68, 68],
  blue: [59, 130, 246],
  darkGray: [26, 26, 26],
  mediumGray: [74, 74, 74],
  lightGray: [107, 114, 128],
  veryLightGray: [229, 231, 235],
  background: [248, 249, 250],
};

/**
 * Generate PDF report matching the approved HTML design
 */
export async function generatePDFReport(data: ReportData): Promise<void> {
  const { location, metrics, dataQuality: _dataQuality } = data;

  const pdf = new jsPDF('p', 'mm', 'a4');
  const pageWidth = pdf.internal.pageSize.getWidth();
  const pageHeight = pdf.internal.pageSize.getHeight();
  const margin = 25;
  const contentWidth = pageWidth - 2 * margin;

  let currentPage = 1;
  void currentPage; // Used for page tracking

  // Helper: Add footer
  const addFooter = (pageNum: number, totalPages: number) => {
    pdf.setFontSize(8);
    pdf.setTextColor(COLORS.lightGray[0], COLORS.lightGray[1], COLORS.lightGray[2]);
    pdf.setFont('helvetica', 'normal');

    const footerText = `Generated by SafeStreets | Data sources: OpenStreetMap, Sentinel-2, NASA POWER, OpenAQ | Page ${pageNum} of ${totalPages}`;
    pdf.text(footerText, pageWidth / 2, pageHeight - 10, { align: 'center' });

    pdf.setTextColor(0, 0, 0);
  };

  // ========================================
  // PAGE 1: Executive Summary
  // ========================================

  let y = margin;

  // Logo
  pdf.setFontSize(10);
  pdf.setTextColor(COLORS.lightGray[0], COLORS.lightGray[1], COLORS.lightGray[2]);
  pdf.setFont('helvetica', 'normal');
  pdf.text('SAFESTREETS', pageWidth / 2, y, { align: 'center' });
  y += 15;

  // Title
  pdf.setFontSize(28);
  pdf.setTextColor(COLORS.darkGray[0], COLORS.darkGray[1], COLORS.darkGray[2]);
  pdf.setFont('helvetica', 'bold');
  pdf.text('Walkability Assessment', pageWidth / 2, y, { align: 'center' });
  y += 12;

  // Location name
  pdf.setFontSize(18);
  pdf.setTextColor(COLORS.mediumGray[0], COLORS.mediumGray[1], COLORS.mediumGray[2]);
  pdf.setFont('helvetica', 'normal');
  pdf.text(location.displayName, pageWidth / 2, y, { align: 'center' });
  y += 25;

  // Score Hero Box
  const heroBoxY = y;
  const heroBoxHeight = 60;

  // Background
  pdf.setFillColor(COLORS.background[0], COLORS.background[1], COLORS.background[2]);
  pdf.roundedRect(margin, heroBoxY, contentWidth, heroBoxHeight, 4, 4, 'F');

  // Score
  const score = metrics.overallScore;
  const scoreColor = score >= 8 ? COLORS.green : score >= 6 ? COLORS.amber : score >= 4 ? COLORS.orange : COLORS.red;

  pdf.setFontSize(72);
  pdf.setTextColor(scoreColor[0], scoreColor[1], scoreColor[2]);
  pdf.setFont('helvetica', 'bold');
  pdf.text(score.toFixed(1), pageWidth / 2 - 15, heroBoxY + 25, { align: 'center' });

  pdf.setFontSize(32);
  pdf.setTextColor(COLORS.lightGray[0], COLORS.lightGray[1], COLORS.lightGray[2]);
  pdf.setFont('helvetica', 'normal');
  pdf.text('/10', pageWidth / 2 + 15, heroBoxY + 25, { align: 'left' });

  // Label
  pdf.setFontSize(20);
  pdf.setTextColor(scoreColor[0], scoreColor[1], scoreColor[2]);
  pdf.setFont('helvetica', 'bold');
  pdf.text(metrics.label, pageWidth / 2, heroBoxY + 35, { align: 'center' });

  // Walker icons (using text)
  const filledWalkers = Math.round(score);
  const emptyWalkers = 10 - filledWalkers;

  pdf.setFontSize(24);
  let walkerX = pageWidth / 2 - 40;
  const walkerY = heroBoxY + 50;

  // Green walkers
  pdf.setTextColor(scoreColor[0], scoreColor[1], scoreColor[2]);
  for (let i = 0; i < filledWalkers; i++) {
    pdf.text('🚶', walkerX, walkerY);
    walkerX += 8;
  }

  // Gray walkers
  pdf.setTextColor(200, 200, 200);
  for (let i = 0; i < emptyWalkers; i++) {
    pdf.text('🚶', walkerX, walkerY);
    walkerX += 8;
  }

  y = heroBoxY + heroBoxHeight + 15;

  // Executive Summary Section
  pdf.setFontSize(16);
  pdf.setTextColor(COLORS.darkGray[0], COLORS.darkGray[1], COLORS.darkGray[2]);
  pdf.setFont('helvetica', 'bold');
  pdf.text('Executive Summary', margin, y);
  y += 2;

  // Underline
  pdf.setDrawColor(COLORS.veryLightGray[0], COLORS.veryLightGray[1], COLORS.veryLightGray[2]);
  pdf.setLineWidth(2);
  pdf.line(margin, y, pageWidth - margin, y);
  y += 10;

  // Summary text
  pdf.setFontSize(11);
  pdf.setTextColor(COLORS.mediumGray[0], COLORS.mediumGray[1], COLORS.mediumGray[2]);
  pdf.setFont('helvetica', 'normal');

  const summaryText1 = `This walkability assessment analyzes six critical factors that determine pedestrian experience and safety in ${location.city || location.displayName}. The overall score of ${score.toFixed(1)}/10 indicates ${metrics.label.toLowerCase()} with notable strengths and areas for improvement.`;

  const summaryLines1 = pdf.splitTextToSize(summaryText1, contentWidth);
  pdf.text(summaryLines1, margin, y);
  y += summaryLines1.length * 5 + 5;

  const summaryText2 = 'The analysis is based on OpenStreetMap data, satellite imagery, and global walkability standards from NACTO (National Association of City Transportation Officials), GSDG (Global Street Design Guide), and ITDP (Institute for Transportation & Development Policy).';

  const summaryLines2 = pdf.splitTextToSize(summaryText2, contentWidth);
  pdf.text(summaryLines2, margin, y);
  y += summaryLines2.length * 5 + 8;

  // Key Findings
  pdf.setFontSize(12);
  pdf.setTextColor(COLORS.darkGray[0], COLORS.darkGray[1], COLORS.darkGray[2]);
  pdf.setFont('helvetica', 'bold');
  pdf.text('Key Findings:', margin, y);
  y += 8;

  // Helper function to add finding
  const addFinding = (icon: string, text: string) => {
    const boxY = y;
    const boxHeight = 15;

    // Background
    pdf.setFillColor(COLORS.background[0], COLORS.background[1], COLORS.background[2]);
    pdf.roundedRect(margin, boxY, contentWidth, boxHeight, 2, 2, 'F');

    // Icon
    pdf.setFontSize(14);
    pdf.text(icon, margin + 3, boxY + 9);

    // Text
    pdf.setFontSize(10);
    pdf.setTextColor(COLORS.mediumGray[0], COLORS.mediumGray[1], COLORS.mediumGray[2]);
    pdf.setFont('helvetica', 'normal');
    const lines = pdf.splitTextToSize(text, contentWidth - 12);
    pdf.text(lines, margin + 10, boxY + 6);

    y += boxHeight + 3;
  };

  // Top 2 strengths and weaknesses
  const metricsArray = [
    { name: 'Street Crossings', score: metrics.crossingDensity, icon: '🚶', unit: ' per km' },
    { name: 'Street Grid', score: metrics.networkEfficiency, icon: '🏙️', unit: 'm blocks' },
    { name: 'Daily Needs', score: metrics.destinationAccess, icon: '🏪', unit: ' types' },
    { name: 'Flat Routes', score: metrics.slope, icon: '🏃', unit: '° slope' },
    { name: 'Tree Canopy', score: metrics.treeCanopy, icon: '🌲', unit: '% canopy' },
    { name: 'Surface Temp', score: metrics.surfaceTemp, icon: '🌡️', unit: '°C' },
    { name: 'Air Quality', score: metrics.airQuality, icon: '💨', unit: ' AQI' },
    { name: 'Heat Island', score: metrics.heatIsland, icon: '🔥', unit: ' index' },
  ].sort((a, b) => b.score - a.score);

  const topMetrics = metricsArray.slice(0, 2);
  const bottomMetrics = metricsArray.slice(-2).reverse();

  topMetrics.forEach(m => {
    addFinding('✅', `${m.name} (${m.score.toFixed(1)}/10): Excellent infrastructure supporting walkability.`);
  });

  bottomMetrics.forEach(m => {
    addFinding('⚠️', `${m.name} (${m.score.toFixed(1)}/10): Significant opportunity for improvement.`);
  });

  // Footer
  addFooter(1, 3);

  // ========================================
  // PAGE 2: Detailed Metrics
  // ========================================

  pdf.addPage();
  currentPage = 2;
  y = margin;

  // Section title
  pdf.setFontSize(20);
  pdf.setTextColor(COLORS.darkGray[0], COLORS.darkGray[1], COLORS.darkGray[2]);
  pdf.setFont('helvetica', 'bold');
  pdf.text('What we measured', margin, y);
  y += 2;

  // Underline
  pdf.setDrawColor(COLORS.veryLightGray[0], COLORS.veryLightGray[1], COLORS.veryLightGray[2]);
  pdf.setLineWidth(2);
  pdf.line(margin, y, pageWidth - margin, y);
  y += 8;

  pdf.setFontSize(11);
  pdf.setTextColor(COLORS.mediumGray[0], COLORS.mediumGray[1], COLORS.mediumGray[2]);
  pdf.setFont('helvetica', 'normal');
  pdf.text('Eight factors that determine how pleasant and safe it is to walk here:', margin, y);
  y += 12;

  // Helper function to draw metric row
  const drawMetric = (icon: string, name: string, score: number, description: string) => {
    const rowY = y;
    const rowHeight = 25;

    // Background
    pdf.setFillColor(COLORS.background[0], COLORS.background[1], COLORS.background[2]);
    pdf.roundedRect(margin, rowY, contentWidth, rowHeight, 3, 3, 'F');

    // Icon
    pdf.setFontSize(24);
    pdf.text(icon, margin + 5, rowY + 15);

    // Metric name
    pdf.setFontSize(13);
    pdf.setTextColor(COLORS.darkGray[0], COLORS.darkGray[1], COLORS.darkGray[2]);
    pdf.setFont('helvetica', 'bold');
    pdf.text(name, margin + 20, rowY + 8);

    // Dots
    const dotX = margin + 20;
    const dotY = rowY + 14;
    const dotSize = 2;
    const dotGap = 3.5;
    const filledDots = Math.round(score);
    const metricColor = score >= 8 ? COLORS.green : score >= 6 ? COLORS.amber : score >= 4 ? COLORS.orange : COLORS.red;

    for (let i = 0; i < 10; i++) {
      if (i < filledDots) {
        pdf.setFillColor(metricColor[0], metricColor[1], metricColor[2]);
      } else {
        pdf.setFillColor(COLORS.veryLightGray[0], COLORS.veryLightGray[1], COLORS.veryLightGray[2]);
      }
      pdf.circle(dotX + i * dotGap, dotY, dotSize, 'F');
    }

    // Description
    pdf.setFontSize(9);
    pdf.setTextColor(COLORS.lightGray[0], COLORS.lightGray[1], COLORS.lightGray[2]);
    pdf.setFont('helvetica', 'normal');
    pdf.text(description, margin + 20, rowY + 20);

    // Score
    pdf.setFontSize(18);
    pdf.setTextColor(metricColor[0], metricColor[1], metricColor[2]);
    pdf.setFont('helvetica', 'bold');
    pdf.text(score.toFixed(1), pageWidth - margin - 15, rowY + 15, { align: 'right' });

    y += rowHeight + 5;
  };

  // Draw all 8 metrics
  drawMetric('🚶', 'Street Crossings', metrics.crossingDensity, 'Marked pedestrian crossings (OpenStreetMap)');
  drawMetric('🏙️', 'Street Grid', metrics.networkEfficiency, 'Block size and street connectivity');
  drawMetric('🏪', 'Daily Needs', metrics.destinationAccess, 'Essential services nearby (OpenStreetMap)');
  drawMetric('🏃', 'Flat Routes', metrics.slope, 'Terrain difficulty (NASADEM)');
  drawMetric('🌲', 'Tree Canopy', metrics.treeCanopy, 'Shade from trees (Sentinel-2 NDVI)');
  drawMetric('🌡️', 'Surface Temp', metrics.surfaceTemp, 'Surface temperature (NASA POWER)');
  drawMetric('💨', 'Air Quality', metrics.airQuality, 'Air quality index (OpenAQ)');
  drawMetric('🔥', 'Heat Island', metrics.heatIsland, 'Urban heat island (Sentinel-2 SWIR)');

  y += 5;

  // Data Quality Note
  const noteBoxY = y;
  const noteBoxHeight = 20;

  pdf.setFillColor(254, 243, 199); // Light yellow
  pdf.roundedRect(margin, noteBoxY, contentWidth, noteBoxHeight, 2, 2, 'F');

  pdf.setDrawColor(245, 158, 11); // Amber border
  pdf.setLineWidth(2);
  pdf.line(margin, noteBoxY, margin, noteBoxY + noteBoxHeight);

  pdf.setFontSize(11);
  pdf.setTextColor(146, 64, 14); // Dark amber
  pdf.setFont('helvetica', 'bold');
  pdf.text('📊 Data Quality', margin + 5, noteBoxY + 8);

  pdf.setFontSize(9);
  pdf.setTextColor(120, 53, 15);
  pdf.setFont('helvetica', 'normal');
  const noteText = 'This analysis is based on OpenStreetMap data contributed by local mappers. Some infrastructure may not yet be mapped. Satellite data is from Sentinel-2 (tree cover), NASA POWER (temperature), and OpenAQ (air quality).';
  const noteLines = pdf.splitTextToSize(noteText, contentWidth - 10);
  pdf.text(noteLines, margin + 5, noteBoxY + 14);

  // Footer
  addFooter(2, 3);

  // ========================================
  // PAGE 3: Standards Analysis
  // ========================================

  pdf.addPage();
  currentPage = 3;
  y = margin;

  // Section title
  pdf.setFontSize(20);
  pdf.setTextColor(COLORS.darkGray[0], COLORS.darkGray[1], COLORS.darkGray[2]);
  pdf.setFont('helvetica', 'bold');
  pdf.text('How it measures up to global standards', margin, y);
  y += 2;

  // Underline
  pdf.setDrawColor(COLORS.veryLightGray[0], COLORS.veryLightGray[1], COLORS.veryLightGray[2]);
  pdf.setLineWidth(2);
  pdf.line(margin, y, pageWidth - margin, y);
  y += 8;

  pdf.setFontSize(11);
  pdf.setTextColor(COLORS.mediumGray[0], COLORS.mediumGray[1], COLORS.mediumGray[2]);
  pdf.setFont('helvetica', 'normal');
  pdf.text('Comparison against leading urban design frameworks for walkable cities:', margin, y);
  y += 12;

  // Helper function to draw standard comparison
  const drawStandard = (name: string, org: string, metrics: Array<{label: string, value: string, status: 'meets' | 'partial' | 'below'}>) => {
    const boxY = y;
    let boxHeight = 12 + metrics.length * 8 + 2;

    // Background
    pdf.setFillColor(COLORS.background[0], COLORS.background[1], COLORS.background[2]);
    pdf.roundedRect(margin, boxY, contentWidth, boxHeight, 3, 3, 'F');

    // Left border
    pdf.setDrawColor(COLORS.blue[0], COLORS.blue[1], COLORS.blue[2]);
    pdf.setLineWidth(3);
    pdf.line(margin, boxY, margin, boxY + boxHeight);

    // Standard name
    pdf.setFontSize(13);
    pdf.setTextColor(COLORS.darkGray[0], COLORS.darkGray[1], COLORS.darkGray[2]);
    pdf.setFont('helvetica', 'bold');
    pdf.text(name, margin + 8, boxY + 7);

    // Org name
    pdf.setFontSize(9);
    pdf.setTextColor(COLORS.lightGray[0], COLORS.lightGray[1], COLORS.lightGray[2]);
    pdf.setFont('helvetica', 'normal');
    pdf.text(org, margin + 8, boxY + 12);

    let metricY = boxY + 18;

    // Draw each metric
    metrics.forEach(m => {
      // Label
      pdf.setFontSize(10);
      pdf.setTextColor(COLORS.mediumGray[0], COLORS.mediumGray[1], COLORS.mediumGray[2]);
      pdf.setFont('helvetica', 'normal');
      pdf.text(m.label, margin + 8, metricY);

      // Value
      pdf.setTextColor(COLORS.lightGray[0], COLORS.lightGray[1], COLORS.lightGray[2]);
      pdf.text(m.value, pageWidth - margin - 45, metricY);

      // Badge
      const badgeColors = {
        meets: { bg: [209, 250, 229], text: [6, 95, 70] },
        partial: { bg: [254, 215, 170], text: [146, 64, 14] },
        below: { bg: [254, 226, 226], text: [153, 27, 27] },
      };

      const badgeColor = badgeColors[m.status];
      const badgeText = m.status === 'meets' ? 'Meets' : m.status === 'partial' ? 'Partial' : 'Below';

      pdf.setFillColor(badgeColor.bg[0], badgeColor.bg[1], badgeColor.bg[2]);
      pdf.roundedRect(pageWidth - margin - 35, metricY - 4, 28, 6, 2, 2, 'F');

      pdf.setFontSize(8);
      pdf.setTextColor(badgeColor.text[0], badgeColor.text[1], badgeColor.text[2]);
      pdf.setFont('helvetica', 'bold');
      pdf.text(badgeText, pageWidth - margin - 21, metricY, { align: 'center' });

      metricY += 8;
    });

    y += boxHeight + 5;
  };

  // NACTO
  drawStandard(
    'NACTO Urban Street Design Guide',
    'National Association of City Transportation Officials',
    [
      { label: 'Block Size (80-150m recommended)', value: '~95m', status: metrics.networkEfficiency >= 7 ? 'meets' : 'partial' },
      { label: 'Crossing Density (≤200m spacing)', value: `${metrics.crossingDensity.toFixed(1)}/10`, status: metrics.crossingDensity >= 7 ? 'meets' : 'partial' },
      { label: 'Street Shading & Microclimate', value: `${Math.round(metrics.treeCanopy * 10)}%`, status: metrics.treeCanopy >= 7 ? 'meets' : 'partial' },
      { label: 'Accessible Terrain (≤5% grade)', value: 'Good', status: metrics.slope >= 7 ? 'meets' : 'partial' },
    ]
  );

  // GSDG
  drawStandard(
    'Global Street Design Guide (GSDG)',
    'NACTO in collaboration with Global Designing Cities Initiative',
    [
      { label: 'Street Connectivity', value: 'High', status: metrics.networkEfficiency >= 7 ? 'meets' : 'partial' },
      { label: 'Urban Heat Management', value: 'Good', status: metrics.heatIsland >= 7 ? 'meets' : 'partial' },
      { label: 'Air Quality (WHO Guidelines)', value: 'Good', status: metrics.airQuality >= 7 ? 'meets' : 'partial' },
    ]
  );

  // ITDP
  drawStandard(
    'Pedestrians First',
    'Institute for Transportation & Development Policy (ITDP)',
    [
      { label: 'Pedestrian Crossings', value: `${metrics.crossingDensity.toFixed(1)}/10`, status: metrics.crossingDensity >= 6 ? 'meets' : 'partial' },
      { label: '15-Minute City (Services Access)', value: `${metrics.destinationAccess.toFixed(1)}/10`, status: metrics.destinationAccess >= 7 ? 'meets' : 'partial' },
      { label: 'Walking Comfort (Surface Temp)', value: 'Good', status: metrics.surfaceTemp >= 6 ? 'meets' : 'partial' },
      { label: 'Terrain Accessibility (≤5% grade)', value: 'Good', status: metrics.slope >= 7 ? 'meets' : 'partial' },
    ]
  );

  y += 5;

  // Overall Assessment
  const assessBoxY = y;
  const assessBoxHeight = 18;

  pdf.setFillColor(240, 249, 255); // Light blue
  pdf.roundedRect(margin, assessBoxY, contentWidth, assessBoxHeight, 2, 2, 'F');

  pdf.setDrawColor(COLORS.blue[0], COLORS.blue[1], COLORS.blue[2]);
  pdf.setLineWidth(2);
  pdf.line(margin, assessBoxY, margin, assessBoxY + assessBoxHeight);

  pdf.setFontSize(10);
  pdf.setTextColor(COLORS.darkGray[0], COLORS.darkGray[1], COLORS.darkGray[2]);
  pdf.setFont('helvetica', 'bold');
  pdf.text('Overall Assessment:', margin + 5, assessBoxY + 6);

  pdf.setFont('helvetica', 'normal');
  const assessText = `This area demonstrates ${score >= 6 ? 'solid' : 'mixed'} fundamentals in environmental walkability, assessed against NACTO and ITDP principles. ${score < 6 ? 'Key areas for improvement include urban heat management and environmental comfort for pedestrians.' : 'The area meets most international standards for pedestrian environmental comfort.'}`;
  const assessLines = pdf.splitTextToSize(assessText, contentWidth - 10);
  pdf.text(assessLines, margin + 5, assessBoxY + 11);

  // Footer
  addFooter(3, 3);

  // ========================================
  // Save PDF
  // ========================================

  const fileName = `safestreets-${location.city || 'report'}-${Date.now()}.pdf`;
  pdf.save(fileName);
}
